# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ProductTemplet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ProductTemplet
  
  pod ‘AESCrypt-ObjC’
  pod ‘AFNetworking’
  pod 'Aspects'

  pod 'FCUUID'
  pod 'FLAnimatedImage'
  pod 'FMDB'

  pod 'GTMBase64'

  pod 'IQKeyboardManager'
  pod ‘iCarousel’
  
  pod 'JPush'
  pod 'JZLocationConverter'
  
  pod 'KVOController'
  
  pod 'MBProgressHUD'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'Masonry'

  pod 'PopoverView'
  pod 'PPNumberButton'
  
  pod 'SDCycleScrollView'
  pod 'SDWebImage'
  
  pod 'Toast'
  
  pod 'UICKeyChainStore'

  pod 'YBAttributeTextTapAction'
  
  pod ‘YYCache’
  pod 'YYCategories'
  pod ‘YYWebImage’
  pod ‘YYModel’
  pod 'YZPullDownMenu'
  
  pod 'ZYCornerRadius'

  pod 'UMengAnalytics-NO-IDFA'

  pod 'BN_Globle'
  pod 'BN_Kit'
  pod 'BN_Category'
  pod 'BN_View'
  pod 'BN_TableViewCell'
  pod 'BN_CollectionView'
  pod 'BN_ViewHeight'

end
